#!/bin/sh

lb config noauto \
     --architectures 'i386' \
     --linux-flavours '686-pae' \
     --apt-recommends 'false' \
     --apt-source-archives 'false' \
     --apt-indices 'false' \
     --archive-areas "main contrib non-free non-free-firmware" \
     --debian-installer 'live' \
     --debian-installer-distribution 'bookworm' \
     --distribution 'bookworm' \
     --mirror-binary 'https://deb.debian.org/debian' \
     --mirror-binary-security 'https://security.debian.org/debian-security' \
     --mirror-bootstrap 'https://deb.debian.org/debian' \
     --firmware-binary 'true' \
     --firmware-chroot 'true' \
     --security 'true' \
     --memtest 'memtest86+' \
     --image-name 'Lilidog-i386-Minimal-Bookworm-24.04.30' \
     --iso-application 'Lilidog-i386-Minimal-Bookworm' \
     --iso-publisher 'Lilidog-i386-Minimal-bookworm GNU/Linux' \
     --iso-volume 'Lilidog-i386-Minimal-Bookworm' \
     --system 'live' \
     --updates 'true' \
     --win32-loader 'false' \
     --zsync 'false' \
     --quiet \
     "${@}"
